// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/clientA.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ClientA service

func NewClientAEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ClientA service

type ClientAService interface {
	SayHello(ctx context.Context, in *SayRequest, opts ...client.CallOption) (*SayResponse, error)
}

type clientAService struct {
	c    client.Client
	name string
}

func NewClientAService(name string, c client.Client) ClientAService {
	return &clientAService{
		c:    c,
		name: name,
	}
}

func (c *clientAService) SayHello(ctx context.Context, in *SayRequest, opts ...client.CallOption) (*SayResponse, error) {
	req := c.c.NewRequest(c.name, "ClientA.SayHello", in)
	out := new(SayResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ClientA service

type ClientAHandler interface {
	SayHello(context.Context, *SayRequest, *SayResponse) error
}

func RegisterClientAHandler(s server.Server, hdlr ClientAHandler, opts ...server.HandlerOption) error {
	type clientA interface {
		SayHello(ctx context.Context, in *SayRequest, out *SayResponse) error
	}
	type ClientA struct {
		clientA
	}
	h := &clientAHandler{hdlr}
	return s.Handle(s.NewHandler(&ClientA{h}, opts...))
}

type clientAHandler struct {
	ClientAHandler
}

func (h *clientAHandler) SayHello(ctx context.Context, in *SayRequest, out *SayResponse) error {
	return h.ClientAHandler.SayHello(ctx, in, out)
}
